name: kafka-connect-bigquery
lang: java
lang_version: 8
git:
  enable: true
codeowners:
  enable: true
semaphore:
  enable: true
  pipeline_type: cp
  trivy_scan: true
  extra_secrets:
    - kcbq_gcp
  extra_deploy_args: "-Pjenkins"
  extra_build_args: "-Pjenkins"
  generate_connect_changelogs: true
code_artifact:
  enable: true
  package_paths:
    - maven-snapshots/maven/com.wepay.kcbq/kcbq-connector
    - maven-snapshots/maven/com.wepay.kcbq/kcbq-api
    - maven-snapshots/maven/com.wepay.kcbq/kcbq-parent
    - maven-snapshots/maven/com.wepay.kcbq/kcbq-confluent
